# Generated by Django 4.2.1 on 2023-05-14 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_podcastmodel_cover_pic_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoriesmodel',
            name='image',
            field=models.ImageField(upload_to='files'),
        ),
    ]
